# Generated by Django 6.0.4 on 2026-05-08 07:42

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import honeybee.models
import secrets
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MessagingWebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(default=secrets.token_urlsafe, max_length=150, unique=True)),
                ('event_type', models.CharField(max_length=100)),
                ('provider', models.CharField(default='generic', max_length=50)),
                ('payload', models.JSONField(default=dict)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('country', models.CharField(choices=[('IN', 'India (+91)'), ('US', 'United States (+1)'), ('UK', 'United Kingdom (+44)'), ('CA', 'Canada (+1)'), ('AU', 'Australia (+61)'), ('DE', 'Germany (+49)'), ('FR', 'France (+33)'), ('JP', 'Japan (+81)'), ('CN', 'China (+86)'), ('BR', 'Brazil (+55)')], max_length=5)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('bio', models.TextField(blank=True)),
                ('match_radius_km', models.PositiveIntegerField(default=50)),
                ('match_dominance_preferences', models.JSONField(blank=True, default=list, validators=[honeybee.models.validate_dominance_choices])),
                ('tier', models.IntegerField(choices=[(0, 'Free'), (1, 'Pro'), (2, 'Premium')], default=0)),
                ('is_verified', models.BooleanField(default=False)),
                ('sex', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('ftm', 'Female to Male'), ('mtf', 'Male to Female'), ('non_binary', 'Non-binary'), ('other', 'Other')], max_length=20)),
                ('orientation', models.CharField(choices=[('straight', 'Straight'), ('gay', 'Gay'), ('lesbian', 'Lesbian'), ('bisexual', 'Bisexual'), ('asexual', 'Asexual'), ('pansexual', 'Pansexual'), ('queer', 'Queer'), ('other', 'Other')], max_length=20)),
                ('lowres_pictures_urls', models.JSONField(blank=True, default=list, validators=[honeybee.models.validate_json_url_list])),
                ('highres_pictures_urls', models.JSONField(blank=True, default=list, validators=[honeybee.models.validate_json_url_list])),
                ('dominance', models.JSONField(blank=True, default=list, validators=[honeybee.models.validate_dominance_choices])),
                ('messaging_external_id', models.CharField(blank=True, max_length=150, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('kinks', models.ManyToManyField(blank=True, related_name='users', to='honeybee.kink')),
            ],
            options={
                'ordering': ['-created_at'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(default=secrets.token_urlsafe, max_length=64, unique=True)),
                ('provider_thread_id', models.CharField(blank=True, max_length=150, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('participants', models.ManyToManyField(related_name='conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('inbound', 'Inbound'), ('outbound', 'Outbound')], max_length=10)),
                ('body', models.TextField()),
                ('provider_message_id', models.CharField(blank=True, max_length=150, null=True, unique=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='honeybee.conversation')),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_messages', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kinks_in_common_count', models.PositiveIntegerField(default=0)),
                ('score', models.PositiveSmallIntegerField(default=0)),
                ('matched_at', models.DateTimeField(auto_now_add=True)),
                ('kinks_in_common', models.ManyToManyField(blank=True, related_name='matches', to='honeybee.kink')),
                ('matched_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matched_by', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-score', '-matched_at'],
                'constraints': [models.UniqueConstraint(fields=('owner', 'matched_user'), name='unique_match_pair'), models.CheckConstraint(condition=models.Q(('owner', models.F('matched_user')), _negated=True), name='prevent_self_match')],
            },
        ),
    ]
