# Generated by Django 6.0.4 on 2026-05-09 14:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('honeybee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserKink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='kink',
            name='name',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='matched_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='score',
            field=models.PositiveSmallIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='message',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='tier',
            field=models.IntegerField(choices=[(0, 'Free'), (1, 'Pro'), (2, 'Premium')], db_index=True, default=0),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['public_id'], name='honeybee_co_public__e2a88e_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['updated_at'], name='honeybee_co_updated_9f8389_idx'),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['owner', 'matched_user'], name='honeybee_ma_owner_i_ab6d54_idx'),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['score', 'matched_at'], name='honeybee_ma_score_c103ab_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', 'created_at'], name='honeybee_me_convers_80e2d0_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['provider_message_id'], name='honeybee_me_provide_baaeca_idx'),
        ),
        migrations.AddIndex(
            model_name='messagingwebhookevent',
            index=models.Index(fields=['event_id'], name='honeybee_me_event_i_31d703_idx'),
        ),
        migrations.AddIndex(
            model_name='messagingwebhookevent',
            index=models.Index(fields=['event_type', 'provider'], name='honeybee_me_event_t_edf78e_idx'),
        ),
        migrations.AddIndex(
            model_name='messagingwebhookevent',
            index=models.Index(fields=['processed_at'], name='honeybee_me_process_d34663_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='honeybee_us_email_f0f91c_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['tier', 'is_verified'], name='honeybee_us_tier_044ad6_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['country', 'sex', 'orientation'], name='honeybee_us_country_8f9df0_idx'),
        ),
        migrations.AddField(
            model_name='userkink',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_kinks', to=settings.AUTH_USER_MODEL),
        ),
    ]
