# Generated by Django 6.0.4 on 2026-05-09 14:37

import honeybee.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('honeybee', '0002_userkink_alter_kink_name_alter_match_matched_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='kinks_in_common',
        ),
        migrations.RemoveField(
            model_name='user',
            name='kinks',
        ),
        migrations.RemoveField(
            model_name='userkink',
            name='owner',
        ),
        migrations.AddField(
            model_name='match',
            name='kinks_in_common',
            field=models.JSONField(blank=True, default=list, validators=[honeybee.models.validate_kink_choices]),
        ),
        migrations.DeleteModel(
            name='Kink',
        ),
        migrations.AddField(
            model_name='user',
            name='kinks',
            field=models.JSONField(blank=True, default=list, validators=[honeybee.models.validate_kink_choices]),
        ),
        migrations.DeleteModel(
            name='UserKink',
        ),
    ]
